Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2020-12, with the labels that each got.

#63 Highlight Main Menu Items
  asu-navigation-menu.php
  inc/wp-custom-menu.php
Labels: enhancement

#69 Add UDS Alert Banner
  README.md
  acf-json/group_5fb83446640cc.json
  functions.php
  inc/class-uds-notification-banner.php
  inc/widgets.php
  page.php
Labels: enhancement

#73 Fix Main Menu Warnings About Missing Array Keys
  README.md
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  functions.php
  img/admin/menu-hierarchy.png
  inc/enqueue.php
  inc/uds-contextual-help.php
  inc/wp-custom-menu.php
  js/theme.js
  js/theme.min.js
  sass/admin.scss
  sass/admin/_menu_builder.scss
Labels: bug

#74 Readme Update: Special Characters and Structure
  README.md
Labels: documentation

#65 Zalsidiki sidebar margin
  templates-sidebar/sidebar-left.php
  templates-sidebar/sidebar-right.php
Labels: enhancement

#68 Removed class widefat from the sidebar select tag
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  inc/wp-custom-fields.php
  sass/admin/_sidebar-metabox.scss
Labels: enhancement

#67 Zalsidiki search widget
  searchform.php
Labels: enhancement

#66 Customize WordPress Widget Menus for ASU Web Standards theming
  functions.php
  inc/class-uds-custom-walker-widget-nav-menu.php
  inc/navigation-widget.php
Labels: enhancement
