Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-05, with the labels that each got.

#193 Allow Customized Unit Name Text in Footer
  inc/customizer/customizer-settings.php
  inc/render-partials.php
  inc/theme-settings.php
  js/customizer-controls.js
Labels: enhancement

#195 Fix PHP Warnings on Additional Classes
  templates-blocks/blockquote/blockquote.php
  templates-blocks/button/button.php
  templates-blocks/cards/card.php
  templates-blocks/content-sections/image-overlap.php
  templates-blocks/overlay-card/overlay-card.php
Labels: blocks

#191 News post type
  acf-json/group_5ef954da477f5.json
  acf-json/group_60074496e95ba.json
  acf-json/group_6089d6189b18e.json
  acf-json/group_60906f953cd12.json
  archive.php
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  functions.php
  inc/setup.php
  inc/template-tags.php
  inc/wp-rest-api-extensions.php
  index.php
  sass/blocks/_story-hero.scss
  sass/theme.scss
  sass/theme/_single.scss
  single.php
  templates-global/hero.php
  templates-global/story-hero.php
  templates-loop/content-card.php
Labels: enhancement

#201 Fix Hero Button Attributes and Add Support for 'target' and 'rel'
  templates-global/hero.php
Labels: Bug, Simple, Urgent

#202 Updated WYSIWYG Settings on Card Body
  acf-json/group_602edd7eb0e61.json
Labels: Can Wait, Enhancement, Simple
