Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-02, with the labels that each got.

#116 v0.11.0 - Template Streamlining and Block Editor Styles
  acf-json/group_5fbec5336f0cf.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  functions.php
  inc/enqueue.php
  inc/shortcodes.php
  inc/uds-blocks.php
  inc/widgets.php
  js/metaboxes.js
  page.php
  sass/theme/_theme.scss
  screenshot.png
  style.css
  templates-blocks/sample-inner-blocks/sample-inner-blocks.php
  templates-blocks/sample/sample.php
  templates-page/landing.php
Labels: enhancement

#120 Fix WordPress Admin Bar 'Quicklinks'
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: bug

#125 Add White Text and Highlighting Options
  acf-json/group_5ef954da477f5.json
  templates-global/hero.php
Labels: enhancement

#127 Fix Maximum Width for Content Area
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: bug

#124 UDS Headings Block
  acf-json/group_601dab5fa164e.json
  inc/uds-blocks.php
  templates-blocks/headings/headings.php
  templates-blocks/headings/register.php
Labels: blocks, enhancement

#128 Adding UDS Button Block
  acf-json/group_601db250e6c94.json
  inc/uds-blocks.php
  templates-blocks/button/button.php
  templates-blocks/button/register.php
Labels: blocks, enhancement

#129 Add FontAwesome Icons in Editor
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  inc/enqueue.php
  sass/admin.scss
  sass/admin/_fontawesome-fixes.scss
Labels: blocks, enhancement

#131 Replace Dummy Links in Header
  header.php
Labels: bug
