Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-09, with the labels that each got.

#270 Remove Unwanted Pagragraph Tags in Cards
  templates-blocks/cards/card.php
Labels: Blocking Issue, Simple, Fix Soon

#261 Header menu when logged in
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: Enhancement

#264 Grid links with bg image
  acf-json/group_60bf99d0b5ceb.json
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  inc/uds-blocks.php
  sass/admin.scss
  sass/theme/_theme.scss
  templates-blocks/grid-links/grid-links.php
  templates-blocks/grid-links/register.php
Labels: Enhancement

#269 Fix Breaking Upstream Changes
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  inc/class-uds-custom-walker-widget-nav-menu.php
  inc/navigation-widget.php
  inc/shortcodes.php
  sass/theme/_theme.scss
Labels: Bug, Intermediate, Fix Soon

#274 Foldable card - accordion
  acf-json/group_613fc14daf233.json
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.min.css.map
  inc/enqueue.php
  inc/uds-blocks.php
  sass/admin.scss
  templates-blocks/foldable-card/foldable-card.js
  templates-blocks/foldable-card/foldable-card.php
  templates-blocks/foldable-card/register.php
Labels: Blocks, Urgent

#276 Add instructions to foldable cards
  acf-json/group_613fc14daf233.json
Labels: Documentation
