Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-08, with the labels that each got.

#239 Allow for More HTML Characters in Card Body
  templates-blocks/cards/card.php
Labels: Enhancement

#246 Remove Support for Block Widget Editor
  inc/setup.php
  inc/widgets.php
Labels: Bug, Simple, Fix Soon

#240 Allow More Special Characters and Formatting in Cards
  acf-json/group_602edd7eb0e61.json
  inc/tiny-mce.php
  templates-blocks/cards/card.php
Labels: Enhancement

#251 CTA Buttons - main menu
  asu-navigation-menu.php
  inc/enqueue.php
  inc/render-partials.php
  inc/wp-custom-menu.php
  js/admin.js
Labels: Enhancement

#252 Fix Content Placement in Large Heroes
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  sass/blocks/_hero.scss
Labels: Bug, Simple, Urgent

#254 Repair 404 Page Layout
  404.php
Labels: Bug, Simple, Urgent
