Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-06, with the labels that each got.

#210 Fix Auto Syncing Issues / Repair Page Hero JSON File
  acf-json/group_5ef954da477f5.json
  inc/uds-blocks.php
Labels: Blocking Issue, Bug, Simple, Urgent

#208 Header gap issue
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  header.php
  sass/theme/_theme.scss
Labels: Bug

#213 Fix alignment issue on desktop view
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  footer.php
  img/innovation-lockup/on-gold/Number-1-in-the-us-for-innovation-prl-0.png
  img/innovation-lockup/on-gold/Number-1-in-the-us-for-innovation-prl-0@2x.png
  img/innovation-lockup/on-gold/Number-1-in-the-us-for-innovation.png
  sass/theme/_theme.scss
Labels: Blocking Issue

#221 404 page
  404.php
Labels: Bug

#217 Header text Highlights
  inc/enqueue.php
  js/heading-highlights.js
Labels: Blocks, Enhancement

#222 Fix Button/Headline Placement in Page Hero
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  js/theme.min.js
  sass/theme/_theme.scss
  src/sass/bootstrap-asu-extends.scss
  src/sass/design-tokens/_variables.scss
  src/sass/extends/_anchor-menu.scss
  src/sass/extends/_blockquotes.scss
  src/sass/extends/_card-and-image.scss
  src/sass/extends/_cards.scss
  src/sass/extends/_charts-and-graphs.scss
  src/sass/extends/_grid-links.scss
  src/sass/extends/_headings.scss
  src/sass/extends/_tooltips.scss
  src/sass/extends/_typography.scss
  src/sass/variables/_typography.scss
Labels: Bug, Simple, Urgent

#220 Core/image block
  css/theme.css
  css/theme.css.map
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: Blocks, Bug
