Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-04, with the labels that each got.

#166 Fix anchor issues with tabs and accordion
  inc/scroll-to-div.php
Labels: bug

#163 Multi-Button Heroes and Hero Image Alt Tags
  acf-json/group_5ef954da477f5.json
  acf-json/group_601db250e6c94.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
  templates-global/hero.php
Labels: enhancement

#168 Add External Link Icons to Menus
  acf-json/group_5f3345f93ac4c.json
  acf-json/group_606366540821f.json
  asu-footer-menu.php
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.min.css.map
  inc/class-uds-custom-walker-widget-nav-menu.php
  inc/wp-custom-menu.php
  sass/admin.scss
Labels: enhancement

#172 External Link Updates
  acf-json/group_606366540821f.json
  asu-footer-menu.php
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.min.css.map
  inc/class-uds-custom-walker-widget-nav-menu.php
  inc/wp-custom-menu.php
  sass/admin.scss
Labels: enhancement

#167 Hero Video
  acf-json/group_5ef954da477f5.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  js/hero_video.js
  sass/theme/_theme.scss
  templates-global/hero.php
Labels: enhancement

#174 Add Alt Tag to Card Images
  acf-json/group_602edd7eb0e61.json
  templates-blocks/cards/card.php
Labels: blocks, enhancement

#151 core/list block
  .jshintignore
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  js/core-list-block.js
  sass/theme/_theme.scss
Labels: blocks, enhancement

#177 Fix addEventListener of null error on video hero
  js/hero_video.js
Labels: bug

#181 Fix the side-scroll issue caused by footer
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: bug

#180 Fix the side scrolling on video hero
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: bug

#176 Back to top button
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  header.php
  inc/enqueue.php
  js/back_to_top.js
  sass/theme/_theme.scss
Labels: enhancement

#183 Fix 'Phantom' Div Created by Banner Widget Area
  inc/class-uds-notification-banner.php
  templates-global/global-banner.php
Labels: enhancement

#187 Fix color-picker.scss
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_color-picker.scss
Labels: bug

#185 Fix hero URL option
  templates-global/hero.php
Labels: bug

#186 Updated core/separator block
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  js/core-divider.js
  sass/theme/_theme.scss
Labels: enhancement

#182 fixed issues with program cards
  acf-json/group_60621c6a16f6b.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  inc/uds-blocks.php
  js/overlay-card.js
  sass/blocks/_program-card.scss
  templates-blocks/overlay-card/overlay-card.php
  templates-blocks/overlay-card/register.php
Labels: blocking issue
