Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2021-03, with the labels that each got.

#136 Card Block
  acf-json/group_602edd7eb0e61.json
  inc/uds-blocks.php
  templates-blocks/cards/card.php
  templates-blocks/cards/register.php
Labels: blocks, enhancement

#137 Allow New Blocks Inside Image-Overlap
  templates-blocks/content-sections/image-overlap.php
Labels: enhancement

#140 ReadMe: Updated Local Dev Instructions
  README.md
  img/admin/local-by-flywheel-connect-area.png
  img/admin/local-by-flywheel-connect.png
Labels: documentation

#145 Remove Core Block Patterns
  inc/uds-blocks.php
Labels: enhancement

#149 Deleted browserSyncOptions.json file
  README.md
  browserSyncOptions.json
Labels: blocking issue

#123 Blockquote - New markup, new SASS
  acf-json/group_602c62588b08a.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/uds-blocks.php
  package-lock.json
  sass/blocks/blockquote-v2.scss
  sass/theme.scss
  src/sass/design-tokens/_variables.scss
  src/sass/extends/_global-header.scss
  templates-blocks/blockquote/blockquote.php
  templates-blocks/blockquote/register.php
Labels: blocks, enhancement

#154 Hero <img>
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
  templates-global/hero.php
Labels: enhancement

#155 Block Enhancement and Cleanup
  acf-json/group_5ef954da477f5.json
  acf-json/group_5f3345f93ac4c.json
  acf-json/group_5fb83446640cc.json
  acf-json/group_600206c085b03.json
  acf-json/group_60074496e95ba.json
  acf-json/group_600773d1450f1.json
  acf-json/group_601dab5fa164e.json
  acf-json/group_601db250e6c94.json
  acf-json/group_602314dddcc3f.json
  acf-json/group_602c62588b08a.json
  acf-json/group_602edd7eb0e61.json
  inc/class-uds-notification-banner.php
  inc/uds-blocks.php
  templates-blocks/blockquote/blockquote.php
  templates-blocks/blockquote/register.php
  templates-blocks/button/button.php
  templates-blocks/button/register.php
  templates-blocks/cards/card.php
  templates-blocks/cards/register.php
  templates-blocks/content-sections/image-overlap.php
  templates-blocks/content-sections/register.php
  templates-blocks/headings/headings.php
  templates-blocks/headings/register.php
  templates-blocks/sample-inner-blocks/register.php
  templates-blocks/sample-inner-blocks/sample-inner-blocks.php
  templates-blocks/sample/register.php
  templates-blocks/sample/sample.php
  templates-global/hero.php
Labels: blocks, enhancement

#153 Fix the gutenberg_editor_full_width issue
  inc/editor.php
Labels: bug

#148 border-[breakpoint]-side classes
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme.scss
  sass/theme/_responsive-borders.scss
Labels: enhancement

#160 ACF Button Block - make it unclickable in the editor side
  css/theme.css
  sass/theme/_theme.scss
Labels: blocking issue

#164 Program's card
  acf-json/group_60621c6a16f6b.json
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/uds-blocks.php
  sass/blocks/_program-card.scss
  sass/theme.scss
  sass/theme/_theme.scss
  templates-blocks/program-card/program-card.php
  templates-blocks/program-card/register.php
Labels: blocks, enhancement
