Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2022-09, with the labels that each got.

#337 Prevent Google from crawling our Sign In and Sign Out Links
  header.php
Labels: Enhancement, Fix Soon

#320 core/list fix performance issues
  css/admin.css
  css/admin.min.css
  css/admin.min.css.map
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  js/core-list-block.js
  sass/admin.scss
  sass/theme/_theme.scss
  theme.json
Labels: Bug, Blocks

#329 UDS form - cf7
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  sass/theme/_theme.scss
Labels: Enhancement

#344 Update Innovation Banner for 2023
  footer.php
  img/innovation-lockup/on-gold/ASU-2022-Innovation-RGB-for-Digital-Lockup-wide-on-gold.png
  img/innovation-lockup/on-gold/ASU-2022-Innovation-RGB-for-Digital-Lockup-wide-on-gold@2x.png
  img/innovation-lockup/on-gold/ASU-2023-Innovation-RGB-for-Digital-Lockup-wide-on-gold.png
  img/innovation-lockup/on-gold/ASU-2023-Innovation-RGB-for-Digital-Lockup-wide-on-gold@2x.png
  src/img/asu-unity/innovation-lockup/on-gold/ASU-2023-Innovation-RGB-for-Digital-Lockup-wide-on-gold.png
  src/img/asu-unity/innovation-lockup/on-gold/ASU-2023-Innovation-RGB-for-Digital-Lockup-wide-on-gold@2x.png
Labels: Enhancement, Web Standards
