Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2022-12, with the labels that each got.

#353 fix scroll behavior when click a[href^="#"]
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  functions.php
  inc/scroll-to-div.php
  sass/theme/_theme.scss
Labels: Bug

#350 core/image
  css/theme.css
  css/theme.min.css
  css/theme.min.css.map
  inc/enqueue.php
  js/core-image-block.js
  sass/theme/_theme.scss
Labels: Blocks

#354 Add Maroon and Gold Icons To Cards
  acf-json/group_602edd7eb0e61.json
  templates-blocks/cards/card.php
Labels: Enhancement
