Repository ASU-KE/UDS-WordPress-Theme, pull requests merged in 2025-04, with the labels that each got.

#552 social media icons: aria label regex update
  inc/class-wp-social-media-walker.php
Labels: Accessibility

#555 Fix Issues with ACF-Based Page Hero
  acf-json/group_5ef954da477f5.json
  templates-global/hero.php
Labels: Bug, Simple, Urgent, Cleanup, Web Standards

#549 404.php, deprecated feature: v1 hero
  404.php
  dist/css/theme.min.css
  dist/css/theme.min.css.map
  src/css/compiled-sass/theme.css
  src/css/compiled-sass/theme.css.map
  src/sass/blocks/_hero.scss
  src/sass/theme.scss
Labels: Cleanup, Web Standards

#548 v1.6 April
  404.php
  README.md
  acf-json/group_5ef954da477f5.json
  dist/css/theme.min.css
  dist/css/theme.min.css.map
  dist/js/theme.min.js
  gulpfile.mjs
  inc/class-wp-social-media-walker.php
  inc/enqueue.php
  package-lock.json
  package.json
  src/css/compiled-sass/theme.css
  src/css/compiled-sass/theme.css.map
  src/js/custom/init-uds-header.js
  src/js/theme.js
  src/js/uds-asu-header/assets/img/arizona-state-university-logo-vertical.png
  src/js/uds-asu-header/assets/img/arizona-state-university-logo.png
  src/js/uds-asu-header/assets/img/asu-starbucks.png
  src/js/uds-asu-header/asuHeader.umd.js
  src/js/uds-asu-header/asuHeaderFooter.umd.js
  src/js/uds-asu-header/main.d.ts
  src/js/uds-asu-header/vendor.umd.js
  src/js/uds-asu-header/vendor.umd.js.LICENSE.txt
  src/sass/blocks/_hero.scss
  src/sass/theme.scss
  style.css
  templates-blocks/blockquote/blockquote.php
  templates-global/hero.php
Labels: Bug, Accessibility, Cleanup, Web Standards
